# Generated by Django 5.2.1 on 2025-05-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_product_description_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=10)),
                ('nickname', models.CharField(max_length=10)),
                ('age', models.IntegerField(verbose_name=3)),
            ],
        ),
    ]
